# Generated by Django 4.1 on 2022-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website_link', models.URLField()),
                ('job_type', models.CharField(max_length=50)),
                ('date_posted', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('website_link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'News Data',
            },
        ),
    ]
